# Generated by Django 4.1.9 on 2023-05-22 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("calendar_file_str", models.TextField(blank=True, null=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="HebrewDate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64)),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Nissan"),
                            (2, "Iyar"),
                            (3, "Sivan"),
                            (4, "Tammuz"),
                            (5, "Av"),
                            (6, "Elul"),
                            (7, "Tishrei"),
                            (8, "Cheshvan"),
                            (9, "Kislev"),
                            (10, "Tevet"),
                            (11, "Shevat"),
                            (12, "Adar I"),
                            (13, "Adar II"),
                        ]
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                            (13, 13),
                            (14, 14),
                            (15, 15),
                            (16, 16),
                            (17, 17),
                            (18, 18),
                            (19, 19),
                            (20, 20),
                            (21, 21),
                            (22, 22),
                            (23, 23),
                            (24, 24),
                            (25, 25),
                            (26, 26),
                            (27, 27),
                            (28, 28),
                            (29, 29),
                            (30, 30),
                        ]
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("🎂", "Birthday"), ("💍", "Anniversary"), ("🕯️", "Yartzeit")], max_length=20
                    ),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="calendarOf", to="hebcal.calendar"
                    ),
                ),
            ],
        ),
    ]
