# Generated by Django 4.1.9 on 2023-05-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hebcal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hebrewdate",
            name="day",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                    (11, 11),
                    (12, 12),
                    (13, 13),
                    (14, 14),
                    (15, 15),
                    (16, 16),
                    (17, 17),
                    (18, 18),
                    (19, 19),
                    (20, 20),
                    (21, 21),
                    (22, 22),
                    (23, 23),
                    (24, 24),
                    (25, 25),
                    (26, 26),
                    (27, 27),
                    (28, 28),
                    (29, 29),
                    (30, 30),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="hebrewdate",
            name="month",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Nissan"),
                    (2, "Iyar"),
                    (3, "Sivan"),
                    (4, "Tammuz"),
                    (5, "Av"),
                    (6, "Elul"),
                    (7, "Tishrei"),
                    (8, "Cheshvan"),
                    (9, "Kislev"),
                    (10, "Tevet"),
                    (11, "Shevat"),
                    (12, "Adar I"),
                    (13, "Adar II"),
                ]
            ),
        ),
    ]
