# Generated by Django 4.2.7 on 2024-01-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hebcal", "0002_alter_hebrewdate_day_alter_hebrewdate_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hebrewdate",
            name="day",
            field=models.IntegerField(
                choices=[
                    (1, "א"),
                    (2, "ב"),
                    (3, "ג"),
                    (4, "ד"),
                    (5, "ה"),
                    (6, "ו"),
                    (7, "ז"),
                    (8, "ח"),
                    (9, "ט"),
                    (10, "י"),
                    (11, "יא"),
                    (12, "יב"),
                    (13, "יג"),
                    (14, "יד"),
                    (15, "טו"),
                    (16, "טז"),
                    (17, "יז"),
                    (18, "יח"),
                    (19, "יט"),
                    (20, "כ"),
                    (21, "כא"),
                    (22, "כב"),
                    (23, "כג"),
                    (24, "כד"),
                    (25, "כה"),
                    (26, "כו"),
                    (27, "כז"),
                    (28, "כח"),
                    (29, "כט"),
                    (30, "ל"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="hebrewdate",
            name="month",
            field=models.IntegerField(
                choices=[
                    (1, "ניסן"),
                    (2, "אייר"),
                    (3, "סיון"),
                    (4, "תמוז"),
                    (5, "אב"),
                    (6, "אלול"),
                    (7, "תשרי"),
                    (8, "חשון"),
                    (9, "כסלו"),
                    (10, "טבת"),
                    (11, "שבט"),
                    (12, "אדר א׳"),
                    (13, "אדר ב׳"),
                ]
            ),
        ),
    ]
