# Generated by Django 5.0.9 on 2024-09-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hebcal", "0004_alter_calendar_name_alter_calendar_timezone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
