# Generated by Django 5.1.4 on 2025-10-19 21:15

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hebcal', '0008_alter_calendar_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='migrated_at',
            field=models.DateTimeField(blank=True, help_text='When this calendar was migrated to authenticated access', null=True),
        ),
        migrations.CreateModel(
            name='UserCalendarSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('subscription_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, db_index=True, editable=False, length=11, max_length=11, prefix='', unique=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='hebcal.calendar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Subscription',
                'verbose_name_plural': 'Calendar Subscriptions',
                'indexes': [models.Index(fields=['subscription_id'], name='hebcal_user_subscri_3fc0e1_idx')],
                'unique_together': {('user', 'calendar')},
            },
        ),
    ]
