# Generated by Django 5.1.4 on 2025-10-19 21:15

from django.db import migrations


def create_owner_subscriptions(apps, schema_editor):
    """
    Create a subscription for each calendar owner automatically.
    """
    Calendar = apps.get_model("hebcal", "Calendar")
    UserCalendarSubscription = apps.get_model("hebcal", "UserCalendarSubscription")

    created_count = 0
    for calendar in Calendar.objects.all():
        subscription, created = UserCalendarSubscription.objects.get_or_create(
            user=calendar.owner,
            calendar=calendar,
        )
        if created:
            created_count += 1

    print(f"✓ Created {created_count} owner subscriptions")


def reverse_func(apps, schema_editor):
    """Optional: Clean up subscriptions if rolling back."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("hebcal", "0009_add_subscription_models"),
    ]

    operations = [
        migrations.RunPython(create_owner_subscriptions, reverse_func),
    ]
