# Generated by Django 5.1.4 on 2025-10-19 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hebcal', '0010_create_owner_subscriptions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='subscribers',
            field=models.ManyToManyField(help_text='Users who have subscribed to this calendar', related_name='subscribed_calendars', through='hebcal.UserCalendarSubscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
