# Generated by Django 5.1.4 on 2025-10-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hebcal', '0011_calendar_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercalendarsubscription',
            name='alarm_time',
            field=models.IntegerField(default=9, help_text='Hours for alarm reminder (negative values = previous day)'),
        ),
    ]
