# Generated by Django 5.1.4 on 2025-10-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hebcal', '0012_add_alarm_time_to_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercalendarsubscription',
            name='alarm_time',
            field=models.IntegerField(default=9, help_text='Hours for alarm reminder (negative = before midnight, positive = after midnight, supports any value)'),
        ),
    ]
