services:
  docs:
    image: my_hebrew_dates_local_docs
    container_name: my_hebrew_dates_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./my_hebrew_dates:/app/my_hebrew_dates:z
    ports:
      - '9000:9000'
    command: /start-docs
